language: rust
cache: cargo
rust:
  - 1.26.0
  - stable
  - beta
  - nightly
env:
  - CARGO_FEATURES=""
  - CARGO_FEATURES="codespan"
  - CARGO_FEATURES="default"
  - CARGO_FEATURES="default codespan"
matrix:
  allow_failures:
    - rust: nightly
script:
  - cargo build --no-default-features --features "$CARGO_FEATURES" --verbose
  - cargo test --no-default-features --features "$CARGO_FEATURES" --verbose
  - bash -c 'if [[ $CARGO_FEATURES = *"default"* ]]; then
      cargo test --no-default-features --features "$CARGO_FEATURES" --examples --verbose;
    fi'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/0c681f01b4d43f234ffa
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
